name: CI/CD Workflow
on:
  push:
    branches:
      - fix-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/sto/server
            ls
            git checkout main
            git pull origin main
            docker compose up --build -d nest-server
            docker system prune -af
     